name: flutter_application_1
description: "App de comunidade de skate."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  # Firebase será adicionado depois
  # firebase_core: ^2.15.1
  # firebase_auth: ^4.7.3
  # cloud_firestore: ^4.8.5
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/skateparks/
